# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: London Canoe Club
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The London Canoe Club is a membership-based recreational canoeing and kayaking organization 
  operating out of London, Ontario, Canada.
  We offer unlimited free kayak and canoe rentals to members for use in the lake at
  Sharon Creek Conservation Area in Delaware, Ontario, just west of London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://londoncanoekayak.ca" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
twitter_username: LondonCanoeClub
facebook_username: LondonCanoeClubON
instagram_username: londoncanoeclubon
membership_form: https://forms.gle/winWJfazjrvgPzhP8
info_email: information.londoncanoeclub@gmail.com
membership_email: memberships.londoncanoeclub@gmail.com
lesson_email: information.londoncanoeclub@gmail.com
admin_email: admin@londoncanoekayak.ca
logo: images/logo-reversed.jpg
google_analytics: G-TNM3F3FXF0 #379563231

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Build settings
remote_theme: fongandrew/hydeout #pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
